### PR TITLE
remove check for existing ips on local.nat_gateways_count

### LINKED ISSUE #101: Nat instances not created when using pre existing eips
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
Upon enabling the use of nat instances, disabling nat gateways and specifying the correct number of pre-existing eips the. nat instances are not created, this is NOT the case if you do not supply exiting eips, nat instances are created correctly in that instance.

## Expected Behavior
Create a VPC
Attach an internet gateway.
Create eips
Standup module for dynamic subnets and. specify nat instances and eips to be used.

Subnets should be created with nat instances in public subnets using the pre existing eips

## Steps to Reproduce
1. Get test code from [this gist](https://gist.github.com/krystan/d2dbbd2e4938cc5a14587664e7d3923c)
2. create three eips
3. alter tfvars file to have your own eips in.
4. run terraform init and run
5. Observe that nat instances were not. created.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux
 - Terraform 12.x

## Additional Context
Tried both. manual vpc creation and using a module

### PR DESCRIPTION
**Pull request by joe-niland**
## what
* Removed check which caused NAT instances/gateways not to be created if existing Elastic IPs provided
* It's not clear why this check was added

## why
* We need the ability to assign existing elastic IPs to NAT instances/gateways

## references
* closes #101

### CODE REVIEW

**Comment by joe-niland** [comment]
@etwillbefine I was wondering why this check was added: https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/86/files#diff-994b65bfe2a964a586187336675fc84a4099482f4444273426a95fc0a79f62c7R11

This PR removes it but it'd be good to know if it served a particular purpose, as I am not sure!

**Review by maximmi — APPROVED** [review]
@joe-niland  I don't know why this check was implemented in first place, but as soon as this fix makes things works it LGTM

**Review by Nuru — CHANGES_REQUESTED** [review]
@joe-niland @osterman @aknysh I am worried this PR changes the existing behavior in an incompatible way. Despite the language in #42, which was closed by PR #86 which introduced "existing IPs", and the description of the `existing_nat_ips`, the current behavior is that if you provide existing IPs, they are assumed to be connected to existing NAT gateways or instances. No new gateways are created. "existing_nat_ips" is interpreted to mean the IPs of existing NATs. 

That said, the existing behavior makes no sense. Nothing is done with the existing IPs, all that happens is that if you provide them, no NATs are created. The same effect could be achieved by setting both `nat_gateway_enabled` and `nat_instance_enabled` to `false`.

So I propose a breaking change that renames `existing_nat_ips` to anything else, maybe `nat_elastic_ips`, so that anyone using `existing_nat_ips` will be notified about the change in behavior, which otherwise could go unnoticed and be expensive.

**Comment by joe-niland** [comment]
@Nuru @maximmi sorry, I should have pinged you guys directly.

@Nuru great point. I agree that the original intention of this variable seems to be to support existing NAT devices. It seems that there was an attempt at https://github.com/cloudposse/terraform-aws-dynamic-subnets/blob/master/nat-gateway.tf#L35 but it's contradicted by the check above.

I didn't consider the important cost implication of this change!

I've made the suggested change.

**Comment by osterman** [comment]
I agree with @Nuru 's recommendations.

**Comment by osterman** [comment]
(I take responsiblity for #86 =) - I thought it was just reusing existing Elastic IPs and associating them with a new NAT gateway or instance)

**Review by osterman — APPROVED** [review]

**Pull request merged**
