### PR TITLE
support using existing elastic ips

### PR DESCRIPTION
**Pull request by etwillbefine**
closes https://github.com/cloudposse/terraform-aws-dynamic-subnets/issues/42

## what
Allow use of existing AWS Elastic IPs by IP address (resolves to allocation id via data source). 

## why
Sometimes its important to keep IP addresses for example to allow business customers granting these IPs in firewalls, a third party tool is configured to only allow certain IPs or there is already an existing IP pool to use. See also referenced issue.

/cc @osterman maybe? :)

### CODE REVIEW

**Comment by etwillbefine** [comment]
Hey, any update on this? Not sure why the checks are failing though

**Comment by osterman** [comment]
@etwillbefine we have some more folks who can help review this now once you rebase and fix the merge conflicts. Tests have been moved to github actions.

**Comment by osterman** [comment]
Tests are failing...
image

**Comment by osterman** [comment]
(only @cloudposse/contributors can run chat ops commands)

**Comment by etwillbefine** [comment]
Sorry, I had an outdated build-harness version installed. Hopefully Tests can fully pass now.

**Pull request merged**
