### PR TITLE
tfsec ignores added/fixed

### PR DESCRIPTION
**Pull request by davenicoll**
## what
* Changed tfsec ignore comments to use the rule name, rather than deprecated IDs
* Added ignores to public and private so that tfsec passes the module without CRITICAL issues

## why
* tfsec no longer supports `#tfsec:ignore:AWS012` style comments
* False positives generated by this module have been ignored

### CODE REVIEW

**Comment by davenicoll** [comment]
make github

**Comment by jamengual** [comment]
@max-lobur is there anything @davenicoll or me needs to do to fix this? ``` reviewdog: This GitHub token doesn't have write permission of Review API [1], 
  so reviewdog will report results via logging command [2] and create annotations similar to```

**Comment by max-lobur** [comment]
> @max-lobur is there anything @davenicoll or me needs to do to fix this? ` reviewdog: This GitHub token doesn't have write permission of Review API [1], so reviewdog will report results via logging command [2] and create annotations similar to`

This is expected for forks. 
But the original tflint complaint looks weird though

Screen Shot 2023-05-18 at 3 13 20 PM

**Comment by max-lobur** [comment]
This should fix it https://github.com/cloudposse/terraform-aws-dynamic-subnets/pull/180

**Review by max-lobur — APPROVED** [review]

**Pull request merged**
